// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gfleingkxbxgcvxspwkd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdmbGVpbmdreGJ4Z2N2eHNwd2tkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkxMjIzNjksImV4cCI6MjA2NDY5ODM2OX0.1KJdEn9xcLdmGaYg3_LLaVzHAvXO0zx7CR5UFONBCN0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);